config/routes.rb
Rails.application.routes.draw do
  resources :spaces
  resources :requests
  devise_for :users
  root 'visitors#index'
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :space
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user
  has_many :requests
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :spaces
  has_many :requests
end

app/controllers/requests_controller.rb
# frozen_string_literal: true

class RequestsController < ApplicationController
  before_action :authenticate_user!

  def index
    @requests_by_user = current_user.requests
    @request_for_user = current_user.spaces.map(&:requests)
  end

  private

  def set_post
    @request = Request.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def request_params
    params.require(:request).permit(:space_id, :booked_date).merge(user_id: current_user.id)
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_space, only: [:show, :edit, :update, :destroy]

  # GET /spaces
  # GET /spaces.json
  def index
    @spaces = Space.all
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(space_params)

    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /spaces/1
  # PATCH/PUT /spaces/1.json
  def update
    # check that owner is the same as the user e.g is_user?(@space.user)
    respond_to do |format|
      if @space.update(space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url, notice: 'Space was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_space
    @space = Space.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def space_params
    params.require(:space).permit(:name, :description, :price_per_night, :available_from, :available_to).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then "alert-info"
    when 'success' then "alert-success"
    when 'error' then "alert-danger"
    when 'alert' then "alert-warning"
    end
  end

  def is_owner?(user)
     user == current_user
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
  def convert_state(state)
    case state
    when 0 then 'bg-warning'
    when 1 then 'bg-danger'
    when 2 then 'bg-success'
    end
  end
end

app/views/layouts/_navigation.erb
<nav class="navbar navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><span class="glyphicon glyphicon-equalizer"></span></a>
      <p class="navbar-text">BnB Challange</p>
<!--      need to add title for website-->
    </div>

    <%= render 'layouts/navigation_links' %>
  </div>
</nav>

app/views/requests/_form.erb
<%= simple_form_for(@request) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/requests/_request.erb
<div class="card text-white <%= convert_state(request.state) %> mb-3" style="max-width: 18rem;">
  <div class="card-header">Requested for: <%= request.booked_date %></div>
  <div class="card-body">
    <h5 class="card-title"><%= request.space.name%></h5>
    <p class="card-text"><%= request.space.description%></p>
  </div>
  <div class="card-footer">Date request made: <%= request.updated_at %></div>

</div>

app/views/requests/index.erb
<div class="row">
  <div class="col-xs-6">
    <h1>My Requests</h1>
    <% @requests_by_user.each do |request| %>
      <%= render request %>
    <%end %>
  </div>
  <div class="col-xs-6">
    <h1>Incoming Requests</h1>
    <% @request_for_user.each do |request| %>
      <%= render request %>
    <%end %>
  </div>
</div>

app/views/spaces/_space.erb
<tr>
  <td><%= space.name %></td>
  <td><%= space.description %></td>
  <td><%= space.price_per_night %></td>
  <td><%= space.available_from %></td>
  <td><%= space.available_to %></td>
  <td><%= link_to 'Show', space %></td>
  <% if(is_owner?(space.user)) %>
    <td><%= link_to 'Edit', edit_space_path(space) %></td>
    <td><%= link_to 'Destroy', space, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</tr>

app/views/spaces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spaces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price per night</th>
      <th>Available from</th>
      <th>Available to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spaces.each do |space| %>
      <%= render space %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Space', new_space_path %>

app/views/spaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @space.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @space.description %>
</p>

<p>
  <strong>Price per night:</strong>
  <%= @space.price_per_night %>
</p>

<p>
  <strong>Available from:</strong>
  <%= @space.available_from %>
</p>

<p>
  <strong>Available to:</strong>
  <%= @space.available_to %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @space.user.email %>
</p>
<% if(is_owner?(@space.user)) %>
  <%= link_to 'Edit', edit_space_path(@space) %> |
<% end %>
<%= link_to 'Back', spaces_path %>

app/views/visitors/index.erb
<div style="width:100%;height:0;padding-bottom:43%;position:relative;"><iframe src="https://giphy.com/embed/26xBwdIuRJiAIqHwA" width="100%" height="100%" style="position:absolute" frameborder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/art-animation-hello-26xBwdIuRJiAIqHwA"></a></p></div>